/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-10-01 08:30:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class categories_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/includes/script.jsp", Long.valueOf(1473930949282L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"/MedicalGap/resources/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<title>Categories</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#listSCat {\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("#selectCategorie{\r\n");
      out.write("   width: 300px;\r\n");
      out.write("   \tfont-size: 16px;\r\n");
      out.write("       font-weight: bold;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#selectSCategorie{\r\n");
      out.write("\t width: 300px;\r\n");
      out.write("   \tfont-size: 16px;\r\n");
      out.write("       font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#listSCat{\r\n");
      out.write("\t width: 300px;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    \tfont-size: 15px;\r\n");
      out.write("\t    \t    margin: 0 auto;\r\n");
      out.write("    float: left;\r\n");
      out.write("\t    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_choix{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#listCat{\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-image: url('/MedicalGap/resources/images/background_cat.png'); background-repeat: no-repeat; background-size: 100% auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media only screen \r\n");
      out.write("and (min-device-width : 768px) \r\n");
      out.write("and (max-device-width : 1024px) \r\n");
      out.write("and (orientation : landscape) {\r\n");
      out.write("  body {\r\n");
      out.write("    background-image: url('/MedicalGap/resources/images/ipad2.png'); background-size: 100% auto;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#bodyCat{ \r\n");
      out.write("\tmargin-right: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen \r\n");
      out.write("and (min-device-width : 768px) \r\n");
      out.write("and (max-device-width : 1024px) \r\n");
      out.write("and (orientation : landscape) {\r\n");
      out.write("  #bodyCat {\r\n");
      out.write("    margin-right: 10px; \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#headerRoche{\r\n");
      out.write("background-image: url('/MedicalGap/resources/images/roche.png'); \r\n");
      out.write("\t\t\tpadding-bottom: 3%;\r\n");
      out.write("\t\t\tmax-height: 57px; max-width: 114px;\r\n");
      out.write("\t\t\tbackground-size: contain;\r\n");
      out.write("\t    \tbackground-repeat: no-repeat; \r\n");
      out.write("\t    \tdisplay: block;\r\n");
      out.write(" \t\t\tmargin-left: auto;\r\n");
      out.write("  \t\t\tmargin-right: auto;\r\n");
      out.write("  \t\t\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#headerLogo{\r\n");
      out.write("background-image: url('/MedicalGap/resources/images/medicalgaplogo.png'); \r\n");
      out.write("\t\t\tpadding-bottom: 3%;\r\n");
      out.write("\t\t\tmax-height: 63px; max-width: 272px;\r\n");
      out.write("\t\t\tbackground-size: contain;\r\n");
      out.write("\t    \tbackground-repeat: no-repeat; \r\n");
      out.write("\t    \tdisplay: block;\r\n");
      out.write(" \t\t\tmargin-left: auto;\r\n");
      out.write("  \t\t\tmargin-right: auto;\r\n");
      out.write("  \t\t\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\" id=\"bodyCaI\">\r\n");
      out.write("\t<div  class=\"container-fluid pull-right\" id=\"bodyCat\"\r\n");
      out.write("\t\tstyle=\"height: 320px; width: 348px; margin-top: 200px;   background-image: url('/MedicalGap/resources/images/311.png'); background-repeat: no-repeat; background-size: 100% 100%;\">\r\n");
      out.write("\t\t<div class=\"container-fluid\" style=\"margin-top: 150px; text-align:center;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"selectCategorie\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary dropdown-toggle\" type=\"button\" onclick=\"clickC();\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\">Selectionnez une catégorie  &nbsp;&nbsp;<span class=\"caret\" ></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" id=\"listCat\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\" id=\"sousC\" onclick=\"chooseCat();\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"selectSCategorie\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary dropdown-toggle\" type=\"button\" onclick=\"clickSSC();\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\tSelectionnez une sous-catégorie   <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" id=\"listSCat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"/MedicalGap/registres/registre\" href=\"#\" onclick=\"clickSC();\">Registres des cancers</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"/MedicalGap/congresses/congresses\" href=\"#\" onclick=\"clickSC();\">Congresses</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"/MedicalGap/tae/tae\" href=\"#\" onclick=\"clickSC();\">TAE</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"/MedicalGap/pressesantes/pressesantes\" href=\"#\" onclick=\"clickSC();\">Presse sante</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"/MedicalGap/guidelines/guidelines\" href=\"#\" onclick=\"clickSC();\">Guidelines</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"/MedicalGap/medicaleactivities/medicaleactivities\" href=\"#\" onclick=\"clickSC();\">Medical activities</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"Cbtn_choix\" class=\"form-group col-ms-5 pull-right\" style=\"margin-top: 10px\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn_choix\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"submit();\" disabled>Accéder</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade bs-example-modal-sm\" id=\"myModal\" tabindex=\"-1\"\r\n");
      out.write("\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-sm\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content \">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-body\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\tSelectionnez une catégorie\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('.combobox').combobox();\r\n");
      out.write("\t\t\t$('form').submit(function(e) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar bodyCat = document.getElementById('bodyCat');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction clickC(){\r\n");
      out.write("\t\t\t\timg = '/MedicalGap/resources/images/435.png';\r\n");
      out.write("\t\t\t\t$(\"#bodyCat\").css({ 'height': '435px' });\r\n");
      out.write("\t\t\t\t$(\"#bodyCat\").css({ 'background-image': 'url('+img+')' });  \r\n");
      out.write("\t\t\t\t$(\"#Cbtn_choix\").css({ 'margin-top': '114px' });\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfunction clickSC(){\r\n");
      out.write("\t\t\t\timg = '/MedicalGap/resources/images/311.png';\r\n");
      out.write("\t\t\t\t$(\"#bodyCat\").css({ 'height': '320px' });\r\n");
      out.write("\t\t\t\t$(\"#bodyCat\").css({ 'background-image': 'url('+img+')' });  \r\n");
      out.write("\t\t\t\t$(\"#Cbtn_choix\").css({ 'margin-top': '10px' });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tfunction clickSSC(){\r\n");
      out.write("\t\t\t\timg = '/MedicalGap/resources/images/509.png';\r\n");
      out.write("\t\t\t\t$(\"#bodyCat\").css({ 'height': '509px' });\r\n");
      out.write("\t\t\t\t$(\"#bodyCat\").css({ 'background-image': 'url('+img+')' });  \r\n");
      out.write("\t\t\t\t$(\"#Cbtn_choix\").css({ 'margin-top': '175px' });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar testC = \"\";\r\n");
      out.write("\t\tvar CC = \"\";\r\n");
      out.write("\t\tvar CS = \"\";\r\n");
      out.write("\t\tfunction getEventTarget(e) {\r\n");
      out.write("\t\t\te = e || window.event;\r\n");
      out.write("\t\t\treturn e.target || e.srcElement;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar li = document.getElementById('listCat');\r\n");
      out.write("\t\tli.onclick = function(event) {\r\n");
      out.write("\t\t\tvar target = getEventTarget(event);\r\n");
      out.write("\t\t\tvar t = target.innerHTML;\r\n");
      out.write("\t\t\t//document.getElementById('selectCat').innerHTML = target.innerHTML.Text;\r\n");
      out.write("\t\t\tdocument.getElementById(\"selectCategorie\").innerHTML = t;\r\n");
      out.write("\t\t\tdocument.getElementById(\"selectSCategorie\").innerHTML = 'Selectionnez une sous-catégorie &nbsp;&nbsp;<span class=\"caret\"></span>';\r\n");
      out.write("\t\t\tdocument.getElementById(\"listSCat\").style.visibility = 'visible';\r\n");
      out.write("\t\t\ttestC = \"ok\";\r\n");
      out.write("\t\t\tCC = t;\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar lt = document.getElementById('listSCat');\r\n");
      out.write("\t\tlt.onclick = function(event) {\r\n");
      out.write("\t\t\tvar target = getEventTarget(event);\r\n");
      out.write("\t\t\tvar t = target.innerHTML;\r\n");
      out.write("\t\t\t//document.getElementById('selectCat').innerHTML = target.innerHTML.Text;\r\n");
      out.write("\t\t\tdocument.getElementById(\"selectSCategorie\").innerHTML = t;\r\n");
      out.write("\t\t\tdocument.getElementById(\"btn_choix\").disabled = false;\r\n");
      out.write("\t\t\tCS = t;\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfunction chooseCat() {\r\n");
      out.write("\t\t\tif (testC != \"ok\") {\r\n");
      out.write("\t\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tfunction submit() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.post(\"/MedicalGap/redirectCat\", {\r\n");
      out.write("\t\t\t\t\"categorie\" : CC,\r\n");
      out.write("\t\t\t}, function(data) {\r\n");
      out.write("\t\t\t\tif (data === \"200\") {\r\n");
      out.write("\t\t\t\t\tif (CS === \"Registres des cancers\") {\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"/MedicalGap/registres/registre\");\r\n");
      out.write("\t\t\t\t\t} else if (CS === \"Congresses\") {\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"/MedicalGap/congresses/congresses\");\r\n");
      out.write("\t\t\t\t\t} else if (CS === \"TAE\") {\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"/MedicalGap/tae/tae\");\r\n");
      out.write("\t\t\t\t\t} else if (CS === \"Presse sante\") {\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"/MedicalGap/pressesantes/pressesantes\");\r\n");
      out.write("\t\t\t\t\t} else if (CS === \"Guidelines\") {\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"/MedicalGap/guidelines/guidelines\");\r\n");
      out.write("\t\t\t\t\t} else if (CS === \"Medical activities\") {\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"/MedicalGap/medicaleactivities/medicaleactivities\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
      out.write("<script type=\"text/javascript\" charset=\"utf8\"\r\n");
      out.write("\tsrc=\"/MedicalGap/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf8\"\r\n");
      out.write("\tsrc=\"/MedicalGap/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction formSubmit() {\r\n");
      out.write("\t\tdocument.getElementById(\"logoutForm\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar activeSystemClass = $('.list-group-item.active');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//something is entered in search form\r\n");
      out.write("\t\t\t\t\t\t$('#system-search')\r\n");
      out.write("\t\t\t\t\t\t\t\t.keyup(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar that = this;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// affect all table rows on in systems table\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tableBody = $('.table-list-search tbody');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tableRowsClass = $('.table-list-search tbody tr');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('.search-sf').remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttableRowsClass\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.each(function(i, val) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t//Lower text for case insensitive\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar rowText = $(val)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.toLowerCase();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar inputText = $(that)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.toLowerCase();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (inputText != '') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'.search-query-sf')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttableBody\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prepend('<tr class=\"search-query-sf\"><td colspan=\"6\"><strong>Searching for: \"'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthat)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '\"</strong></td></tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'.search-query-sf')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (rowText\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.indexOf(inputText) == -1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//hide rows\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttableRowsClass\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.eq(i)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('.search-sf')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttableRowsClass\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.eq(i)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//all tr elements are hidden\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (tableRowsClass\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.children(':visible').length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttableBody\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append('<tr class=\"search-sf\"><td class=\"text-muted\" colspan=\"6\">No entries found.</td></tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t$.fn.pageMe = function(opts) {\r\n");
      out.write("\t\tvar $this = this, defaults = {\r\n");
      out.write("\t\t\tperPage : 7,\r\n");
      out.write("\t\t\tshowPrevNext : false,\r\n");
      out.write("\t\t\thidePageNumbers : false\r\n");
      out.write("\t\t}, settings = $.extend(defaults, opts);\r\n");
      out.write("\r\n");
      out.write("\t\tvar listElement = $this;\r\n");
      out.write("\t\tvar perPage = settings.perPage;\r\n");
      out.write("\t\tvar children = listElement.children();\r\n");
      out.write("\t\tvar pager = $('.pager');\r\n");
      out.write("\r\n");
      out.write("\t\tif (typeof settings.childSelector != \"undefined\") {\r\n");
      out.write("\t\t\tchildren = listElement.find(settings.childSelector);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (typeof settings.pagerSelector != \"undefined\") {\r\n");
      out.write("\t\t\tpager = $(settings.pagerSelector);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar numItems = children.size();\r\n");
      out.write("\t\tvar numPages = Math.ceil(numItems / perPage);\r\n");
      out.write("\r\n");
      out.write("\t\tpager.data(\"curr\", 0);\r\n");
      out.write("\r\n");
      out.write("\t\tif (settings.showPrevNext) {\r\n");
      out.write("\t\t\t$('<li><a href=\"#\" class=\"prev_link\">Précedent</a></li>').appendTo(pager);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar curr = 0;\r\n");
      out.write("\t\twhile (numPages > curr && (settings.hidePageNumbers == false)) {\r\n");
      out.write("\t\t\t$('<li><a href=\"#\" class=\"page_link\">' + (curr + 1) + '</a></li>')\r\n");
      out.write("\t\t\t\t\t.appendTo(pager);\r\n");
      out.write("\t\t\tcurr++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (settings.showPrevNext) {\r\n");
      out.write("\t\t\t$('<li><a href=\"#\" class=\"next_link\">Suivant</a></li>').appendTo(pager);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tpager.find('.page_link:first').addClass('active');\r\n");
      out.write("\t\tpager.find('.prev_link').hide();\r\n");
      out.write("\t\tif (numPages <= 1) {\r\n");
      out.write("\t\t\tpager.find('.next_link').hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tpager.children().eq(1).addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("\t\tchildren.hide();\r\n");
      out.write("\t\tchildren.slice(0, perPage).show();\r\n");
      out.write("\r\n");
      out.write("\t\tpager.find('li .page_link').click(function() {\r\n");
      out.write("\t\t\tvar clickedPage = $(this).html().valueOf() - 1;\r\n");
      out.write("\t\t\tgoTo(clickedPage, perPage);\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tpager.find('li .prev_link').click(function() {\r\n");
      out.write("\t\t\tprevious();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tpager.find('li .next_link').click(function() {\r\n");
      out.write("\t\t\tnext();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction previous() {\r\n");
      out.write("\t\t\tvar goToPage = parseInt(pager.data(\"curr\")) - 1;\r\n");
      out.write("\t\t\tgoTo(goToPage);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction next() {\r\n");
      out.write("\t\t\tgoToPage = parseInt(pager.data(\"curr\")) + 1;\r\n");
      out.write("\t\t\tgoTo(goToPage);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction goTo(page) {\r\n");
      out.write("\t\t\tvar startAt = page * perPage, endOn = startAt + perPage;\r\n");
      out.write("\r\n");
      out.write("\t\t\tchildren.css('display', 'none').slice(startAt, endOn).show();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (page >= 1) {\r\n");
      out.write("\t\t\t\tpager.find('.prev_link').show();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpager.find('.prev_link').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (page < (numPages - 1)) {\r\n");
      out.write("\t\t\t\tpager.find('.next_link').show();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpager.find('.next_link').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tpager.data(\"curr\", page);\r\n");
      out.write("\t\t\tpager.children().removeClass(\"active\");\r\n");
      out.write("\t\t\tpager.children().eq(page + 1).addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#myTable').pageMe({\r\n");
      out.write("\t\t\tpagerSelector : '#myPager',\r\n");
      out.write("\t\t\tshowPrevNext : true,\r\n");
      out.write("\t\t\thidePageNumbers : false,\r\n");
      out.write("\t\t\tperPage : 6\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t(function ( $ ) {\r\n");
      out.write("\r\n");
      out.write("\t\t$.fn.bootstrapSwitch = function( options ) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar settings = $.extend({\r\n");
      out.write("\t\t\t\ton: 'On',\r\n");
      out.write("\t\t\t\toff: 'Off\t',\r\n");
      out.write("\t\t\t\tonLabel: '&nbsp;&nbsp;&nbsp;',\r\n");
      out.write("\t\t\t\toffLabel: '&nbsp;&nbsp;&nbsp;',\r\n");
      out.write("\t\t\t\tsame: false,//same labels for on/off states\r\n");
      out.write("\t\t\t\tsize: 'md',\r\n");
      out.write("\t\t\t\tonClass: 'primary',\r\n");
      out.write("\t\t\t\toffClass: 'default'\r\n");
      out.write("\t\t\t\t}, options );\r\n");
      out.write("\r\n");
      out.write("\t\t\tsettings.size = ' btn-'+settings.size;\r\n");
      out.write("\t\t\tif (settings.same){\r\n");
      out.write("\t\t\t\tsettings.onLabel = settings.on;\r\n");
      out.write("\t\t\t\tsettings.offLabel = settings.off;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn this.each(function(e) {\r\n");
      out.write("\t\t\t\tvar c = $(this);\r\n");
      out.write("\t\t\t\tvar disabled = c.is(\":disabled\") ? \" disabled\" : \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar div = $('<div class=\"btn-group btn-toggle\" style=\"white-space: nowrap;\"></div>').insertAfter(this);\r\n");
      out.write("\t\t\t\tvar on = $('<button class=\"btn btn-primary '+settings.size+disabled+'\" style=\"float: none;display: inline-block;\"></button>').html(settings.on).css('margin-right', '0px').appendTo(div);\r\n");
      out.write("\t\t\t\tvar off = $('<button class=\"btn btn-danger '+settings.size+disabled+'\" style=\"float: none;display: inline-block;\"></button>').html(settings.off).css('margin-left', '0px').appendTo(div);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfunction applyChange(b) {\r\n");
      out.write("\t\t\t\t\tif(b) {\r\n");
      out.write("\t\t\t\t\t\ton.attr('class', 'btn active btn-' + settings.onClass+settings.size+disabled).html(settings.on).blur();\r\n");
      out.write("\t\t\t\t\t\toff.attr('class', 'btn btn-default '+settings.size+disabled).html(settings.offLabel).blur();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\ton.attr('class', 'btn btn-default '+settings.size+disabled).html(settings.onLabel).blur();\r\n");
      out.write("\t\t\t\t\t\toff.attr('class', 'btn active btn-' + settings.offClass+settings.size+disabled).text(settings.off).blur();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tapplyChange(c.is(':checked'));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\ton.click(function(e) {e.preventDefault();c.prop(\"checked\", !c.prop(\"checked\")).trigger('change')});\r\n");
      out.write("\t\t\t\toff.click(function(e) {e.preventDefault();c.prop(\"checked\", !c.prop(\"checked\")).trigger('change')});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).hide().on('change', function() {\r\n");
      out.write("\t\t\t\t\tapplyChange(c.is(':checked'))\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t} ( jQuery ));\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/categories.jsp(135,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("cat");
    // /WEB-INF/views/categories.jsp(135,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/categories.jsp(135,7) '${listCategories}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listCategories}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categorie}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" href=\"#\" onclick=\"clickSC();\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cat.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/categories.jsp(136,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("categorie");
    // /WEB-INF/views/categories.jsp(136,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/categories.jsp(136,8) '${fn:replace(cat.name , \r\n                                ' ', '')}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_0),"${fn:replace(cat.name , \r\n                                ' ', '')}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
